#!/bin/bash

GPIO=21

#get mode
MODE=1
if [ -e "/etc/motioneye/light.mode" ] ; then
    MODE=$(cat "/etc/motioneye/light.mode")
fi

test -e /sys/class/gpio/gpio$GPIO || echo $GPIO > /sys/class/gpio/export

#if light is flashing, tell user light is not in manual mode
if [ "$MODE" -eq 1 ] ; then
	curl "http://localhost:7999/1/config/set?text_left=Light not manual."
else
echo out > /sys/class/gpio/gpio$GPIO/direction
echo 1 > /sys/class/gpio/gpio$GPIO/value;

fi

